/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgramRouteImport } from './routes/program'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as PendaftaranRouteImport } from './routes/pendaftaran'
import { Route as OrganisasiRouteImport } from './routes/organisasi'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as JobRouteImport } from './routes/job'
import { Route as GaleriRouteImport } from './routes/galeri'
import { Route as ArtikelRouteImport } from './routes/artikel'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'

const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PendaftaranRoute = PendaftaranRouteImport.update({
  id: '/pendaftaran',
  path: '/pendaftaran',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisasiRoute = OrganisasiRouteImport.update({
  id: '/organisasi',
  path: '/organisasi',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const JobRoute = JobRouteImport.update({
  id: '/job',
  path: '/job',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriRoute = GaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelRoute = ArtikelRouteImport.update({
  id: '/artikel',
  path: '/artikel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artikel': typeof ArtikelRoute
  '/galeri': typeof GaleriRoute
  '/job': typeof JobRoute
  '/kontak': typeof KontakRoute
  '/organisasi': typeof OrganisasiRoute
  '/pendaftaran': typeof PendaftaranRoute
  '/profil': typeof ProfilRoute
  '/program': typeof ProgramRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artikel': typeof ArtikelRoute
  '/galeri': typeof GaleriRoute
  '/job': typeof JobRoute
  '/kontak': typeof KontakRoute
  '/organisasi': typeof OrganisasiRoute
  '/pendaftaran': typeof PendaftaranRoute
  '/profil': typeof ProfilRoute
  '/program': typeof ProgramRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artikel': typeof ArtikelRoute
  '/galeri': typeof GaleriRoute
  '/job': typeof JobRoute
  '/kontak': typeof KontakRoute
  '/organisasi': typeof OrganisasiRoute
  '/pendaftaran': typeof PendaftaranRoute
  '/profil': typeof ProfilRoute
  '/program': typeof ProgramRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artikel'
    | '/galeri'
    | '/job'
    | '/kontak'
    | '/organisasi'
    | '/pendaftaran'
    | '/profil'
    | '/program'
    | '/admin/login'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artikel'
    | '/galeri'
    | '/job'
    | '/kontak'
    | '/organisasi'
    | '/pendaftaran'
    | '/profil'
    | '/program'
    | '/admin/login'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/artikel'
    | '/galeri'
    | '/job'
    | '/kontak'
    | '/organisasi'
    | '/pendaftaran'
    | '/profil'
    | '/program'
    | '/admin/login'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtikelRoute: typeof ArtikelRoute
  GaleriRoute: typeof GaleriRoute
  JobRoute: typeof JobRoute
  KontakRoute: typeof KontakRoute
  OrganisasiRoute: typeof OrganisasiRoute
  PendaftaranRoute: typeof PendaftaranRoute
  ProfilRoute: typeof ProfilRoute
  ProgramRoute: typeof ProgramRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pendaftaran': {
      id: '/pendaftaran'
      path: '/pendaftaran'
      fullPath: '/pendaftaran'
      preLoaderRoute: typeof PendaftaranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisasi': {
      id: '/organisasi'
      path: '/organisasi'
      fullPath: '/organisasi'
      preLoaderRoute: typeof OrganisasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job': {
      id: '/job'
      path: '/job'
      fullPath: '/job'
      preLoaderRoute: typeof JobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeri': {
      id: '/galeri'
      path: '/galeri'
      fullPath: '/galeri'
      preLoaderRoute: typeof GaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel': {
      id: '/artikel'
      path: '/artikel'
      fullPath: '/artikel'
      preLoaderRoute: typeof ArtikelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtikelRoute: ArtikelRoute,
  GaleriRoute: GaleriRoute,
  JobRoute: JobRoute,
  KontakRoute: KontakRoute,
  OrganisasiRoute: OrganisasiRoute,
  PendaftaranRoute: PendaftaranRoute,
  ProfilRoute: ProfilRoute,
  ProgramRoute: ProgramRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
